name: Github Action Context, Function, ENV
on: [push]
run-name: ${{github.actor}} pushed to ${{github.ref}}

jobs:
  Context-test:
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: |
          echo "start"

