name: Deploy spring server to Private Server
on: [push]

jobs:
  deploy:
    environment: inputs.env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Build the Docker image
        run: |
          cd ./server-to-test
          echo pwd
          docker build -t dockering-server:0.0.1 .

      - name: Push the Docker image to the registry
        run: docker push juni416/dockering-ser드ver:0.0.1
