name: Our Reusable
show_in_ui: false   # 템플릿 ui목록에서 보여주지 않기

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      default-test:
        type: string
        required: false
        default: "default-test"

jobs:
  deploy:
    environment: inputs.env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to $server
        run: |
          # Add your deployment script or commands here
          echo "Deploying to "${{ inputs.env }}""
          echo "Deploying to "${{ inputs.default-test }}""