name: Deploy spring server to Private Server
on: [push]

jobs:
  deploy:
    environment: inputs.env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - run: |
          echo "Checkout Repository"
          ls -al
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
      - name: Build the Docker image
        run: |
          docker build -t dockering-server:0.0.1 server-to-test/Dockerfile

