name: Deploy Template
on:
  workflow_dispatch:
    deploy_env:
      description: "배포 환경"
      required: true
      type: choice
      options:
        - dev
        - test
        - staging
        - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to $server
        run: |
          # Add your deployment script or commands here
          echo "Deploying to $server"