name: Our Reusable

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  deploy:
    environment: input.env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to $server
        run: |
          # Add your deployment script or commands here
          echo "Deploying to ${{input.env}}"