name: Docker
on: [ push ]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        api_url: some-url.com
      ports:
        - 80
        - 443
    steps:
      - name: Log Node & OS Versions
        run: |
          echo "Node Version: $(node -v)"
          cat /etc/os-release
      - name: Log ENV Variables
        run: |
          echo "API_URL: $API_URL"
      - name: Container in a step
        uses: docker://node:18.16-alpine:3.17
        with:
          entrypoint: /usr/local/bin/node     # 노드를 사용하기 위한 패스 지정(명령어)
          args: -p 2+3
      - name: Container Node Version
        uses: docker://node:18.16-alpine:3.17
        with:
          args: -v
