name: Deploy to Servers

on:
  workflow_dispatch:
    deploy_env:
      description: "배포 환경"
      required: true
      type: choice
      options:
        - dev
        - test
        - staging
        - prod
jobs:
  deploy:
    - name: Deploy to Server1
      uses: ./.github/workflows/deploy-template.yml
      with:
        env: "Server1"
