name: Deploy to Servers

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "배포 환경"
        required: true
        type: choice
        options:
          - dev
          - test
          - staging
          - prod
jobs:
  deploy1:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      env: Server1

  deploy2:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      env: Server1

  deploy3:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      env: ${{github.event.inputs.deploy_env}}