name: Scheduler-every-business-day
on:
    schedule:
      - cron: '0/5 * * * *'
#        - cron: '59 23 * * MON-FRI'
jobs:
  schduler:
    runs-on: ubuntu-latest
#    permissions:
#      issues: write
#      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "this is scheduled issue"

