name: Scheduler-every-business-day
on:
  schedule:
    - cron: "59 23 * * 1-5" # 1,5 is Monday to Friday
    - cron: "0/15 * * * *"
jobs:
  schduler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: One minute scheduler
        run: |
          echo "One minute scheduler"
