name: Variables and Secrets
on: [ push ]

jobs:
  log-vars:
    runs-on: ${{vars.JOBS_RUNNER}}
    env:
      ENV_LEVEL_VAR: ${{vars.ENV_LEVEL_VAR}}
      REPOSITORY_LEVEL_VAR: ${{vars.REPOSITORY_LEVEL_VAR}}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - name: log vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
